<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="EditSeatCategories.aspx.cs" Inherits="EventGlint.Admin.SeatCategories" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
        }

        .form-container {
            width: 400px;
            margin: 60px auto;
            background: white;
            padding: 25px;
            border-radius: 10px;
            box-shadow: 0 4px 10px rgba(0,0,0,0.1);
        }

        .input {
            width: 100%;
            padding: 8px;
            border-radius: 5px;
            border: 1px solid #ccc;
            font-size: 14px;
        }

            .input:focus {
                border-color: #5f5d5b;
                outline: none;
            }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        td {
            padding: 10px;
        }

        .button {
            padding: 8px 18px;
            border: 1px;
            border-radius: 5px;
            background-color: darkslateblue;
            color: white;
            cursor: pointer;
            font-size: 14px;
        }

            .button:hover {
                background-color: white;
                color: darkslateblue;
                border: 1px solid darkslateblue;
            }

        h1 {
            text-align: center;
            color: darkslateblue;
            margin-bottom: 20px;
        }
    </style>

    <title>Edit Seat Categories</title>
</head>
<body>
    <form id="form1" runat="server">
        <div class="form-container">
            <h1>Edit Seat Categories</h1>
            <table>
                <tr>
                    <td>
                        <asp:Label ID="lbl_Hall" runat="server" Text="Hall Name:"></asp:Label>
                    </td>
                    <td>

                        <asp:DropDownList CssClass="input" ID="ddl_Hall" runat="server" AutoPostBack="True">
                        </asp:DropDownList>

                    </td>
                </tr>
                <tr>
                    <td>
                        <asp:Label ID="lbl_Cat" runat="server" Text="Seat Category Name:"></asp:Label>
                    </td>
                    <td>
                        <asp:RadioButton ID="rbt_silver" runat="server" GroupName="cat" Text="Silver" />
                        
                        <br />
                        
                        <asp:RadioButton ID="rbt_gold" runat="server" GroupName="cat" Text="Gold" />
                        <br />
                        <asp:RadioButton ID="rbt_platinum" runat="server" GroupName="cat" Text="Platinum" />
                    </td>
                </tr>
                <tr>
                    <td>
                        <asp:Label ID="lbl_price" runat="server" Text="Price:"></asp:Label>
                    </td>
                    <td>

                        <asp:TextBox CssClass="input" ID="txt_price" runat="server" TextMode="Number"></asp:TextBox>

                    </td>
                </tr>
                <tr>
                    <td>
                        <asp:Label ID="lbl_color" runat="server" Text="Color Code:"></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox CssClass="input" ID="txt_color" runat="server"></asp:TextBox>
                    </td>
                </tr>

                <tr>
                    <td colspan="2" align="center">
                        <asp:Button CssClass="button" ID="btn_Insert" runat="server" Text="Insert" OnClick="btn_Insert_Click" />
                        <asp:Button CssClass="button" ID="btn_Update" runat="server" Text="Update" OnClick="btn_Update_Click" />
                    </td>
                </tr>

            </table>
        </div>

        <asp:GridView ID="gv_Category" runat="server" Style="text-align: center"
            align="center" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True"
            DataKeyNames="CategoryId,HallId" BackColor="White" BorderColor="#E7E7FF"
            BorderStyle="None" BorderWidth="1px" CellPadding="3" GridLines="Horizontal"
            OnRowDeleting="gv_Category_RowDeleting" OnSelectedIndexChanged="gv_Category_SelectedIndexChanged"
            CellSpacing="2" HorizontalAlign="Center">

            <AlternatingRowStyle BackColor="#F7F7F7" />
            <FooterStyle BackColor="#B5C7DE" ForeColor="#4A3C8C" />
            <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#F7F7F7" />
            <PagerStyle BackColor="#E7E7FF" ForeColor="#4A3C8C" HorizontalAlign="Right" />
            <RowStyle BackColor="#E7E7FF" ForeColor="#4A3C8C" />
            <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="#F7F7F7" />
            <SortedAscendingCellStyle BackColor="#F4F4FD" />
            <SortedAscendingHeaderStyle BackColor="#5A4C9D" />
            <SortedDescendingCellStyle BackColor="#D8D8F0" />
            <SortedDescendingHeaderStyle BackColor="#3E3277" />
        </asp:GridView>

    </form>

</body>

</html>
