<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="EditSeats.aspx.cs" Inherits="EventGlint.Admin.EditSeats" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
        }

        .form-container {
            width: 400px;
            margin: 60px auto;
            background: white;
            padding: 25px;
            border-radius: 10px;
            box-shadow: 0 4px 10px rgba(0,0,0,0.1);
        }

        .input {
            width: 100%;
            padding: 8px;
            border-radius: 5px;
            border: 1px solid #ccc;
            font-size: 14px;
        }

            .input:focus {
                border-color: #5f5d5b;
                outline: none;
            }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        td {
            padding: 10px;
        }

        .button {
            border-style: none;
            border-color: inherit;
            border-width: 1px;
            padding: 8px 18px;
            border-radius: 5px;
            background-color: darkslateblue;
            color: white;
            cursor: pointer;
            font-size: 14px;
            height: 38px;
        }

            .button:hover {
                background-color: white;
                color: darkslateblue;
                border: 1px solid darkslateblue;
            }

        h1 {
            text-align: center;
            color: darkslateblue;
            margin-bottom: 20px;
        }
    </style>

    <title>Edit Seat</title>
</head>
<body>
    <form id="form1" runat="server">
        <div class="form-container">
            <h1>Edit Seat</h1>


            <table>
                <tr>
                    <td>
                        <asp:Label ID="lbl_Hall" runat="server" Text="Hall Name:"></asp:Label>
                    </td>
                    <td>

                        <asp:DropDownList CssClass="input" ID="ddl_Hall" runat="server" AutoPostBack="True" OnSelectedIndexChanged="ddl_Hall_SelectedIndexChanged">
                        </asp:DropDownList>

                    </td>
                </tr>
                <tr>
                    <td>
                        <asp:Label ID="lbl_Cat" runat="server" Text="Seat Category Name:"></asp:Label>
                    </td>
                    <td>
                        <asp:DropDownList CssClass="input" ID="ddl_Cat" runat="server" AutoPostBack="True">
                        </asp:DropDownList>
                    </td>
                </tr>
                <tr>
                    <td>
                        <asp:Label ID="lbl_Row" runat="server" Text="Row Label:"></asp:Label>
                    </td>
                    <td>

                        <asp:TextBox CssClass="input" ID="txt_row" runat="server"></asp:TextBox>

                    </td>
                </tr>
                <tr>
                    <td>
                        <asp:Label ID="lbl_Seat" runat="server" Text="Seat Number:"></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox CssClass="input" ID="txt_seat" runat="server" TextMode="Number"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td>
                        <asp:Label ID="lbl_wheel" runat="server" Text="IsWheelChair:"></asp:Label>
                    </td>
                    <td>
                        <asp:RadioButton ID="rbt_yesw" runat="server" GroupName="wheel" Text="Yes" />
                        <asp:RadioButton ID="rbt_now" runat="server" GroupName="wheel" Text="No" />
                    </td>
                </tr>
                <tr>
                    <td>
                        <asp:Label ID="lbl_active" runat="server" Text="IsActive:"></asp:Label>
                    </td>
                    <td>
                        <asp:RadioButton ID="rbt_yesa" runat="server" GroupName="active" Text="Yes" />
                        &nbsp;
                        <asp:RadioButton ID="rbt_noa" runat="server" GroupName="active" Text="No" />
                    </td>
                </tr>

                <tr>
                    <td colspan="2" align="center">
                        <asp:Button CssClass="button" ID="btn_Insert" runat="server" Text="Insert" OnClick="btn_Insert_Click" />
                        <asp:Button CssClass="button" ID="btn_Update" runat="server" Text="Update" OnClick="btn_Update_Click" />
                    </td>
                </tr>

            </table>
        </div>

        <asp:GridView ID="gv_Seat" runat="server" Style="text-align: center"
            align="center" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True"
            DataKeyNames="SeatId,HallId,CategoryId" BackColor="White" BorderColor="#E7E7FF"
            BorderStyle="None" BorderWidth="1px" CellPadding="3" GridLines="Horizontal"
            OnRowDeleting="gv_Seat_RowDeleting" OnSelectedIndexChanged="gv_Seat_SelectedIndexChanged"
            CellSpacing="2" HorizontalAlign="Center" Width="70%">

            <AlternatingRowStyle BackColor="#F7F7F7" />
            <FooterStyle BackColor="#B5C7DE" ForeColor="#4A3C8C" />
            <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#F7F7F7" />
            <PagerStyle BackColor="#E7E7FF" ForeColor="#4A3C8C" HorizontalAlign="Right" />
            <RowStyle BackColor="#E7E7FF" ForeColor="#4A3C8C" />
            <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="#F7F7F7" />
            <SortedAscendingCellStyle BackColor="#F4F4FD" />
            <SortedAscendingHeaderStyle BackColor="#5A4C9D" />
            <SortedDescendingCellStyle BackColor="#D8D8F0" />
            <SortedDescendingHeaderStyle BackColor="#3E3277" />
        </asp:GridView>

    </form>

</body>

</html>
